name: test my project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: make install
    - name: make-lint
      run: make lint 
      